### ISSUE TITLE
ERROR i.g.z.a.s.u.t.m.TrackingServiceImpl - Error occurred while tacking

### ISSUE THREAD

**Issue by ojacques** [devops-dojo/the-app#23]
Logs filling with errors on Monolithic app server, in /var/log/tomcat7/appstash.log:
```
Error occurred while tacking
java.lang.NullPointerException: null
        at io.github.zutherb.appstash.shop.ui.tracking.mixpanel.TrackingServiceImpl.trackProductView(TrackingServiceImpl.java:104) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480) [wicket-ioc-7.0.0-M6.jar:7.0.0-M6]
        at com.sun.proxy.$Proxy57.trackProductView(Unknown Source) [na:na]
        at io.github.zutherb.appstash.shop.ui.page.catalog.ProductCatalogPage.onBeforeRender(ProductCatalogPage.java:68) [classes/:na]
        at org.apache.wicket.Component.internalBeforeRender(Component.java:949) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.Component.beforeRender(Component.java:1017) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.Component.internalPrepareForRender(Component.java:2214) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.Page.internalPrepareForRender(Page.java:242) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.Component.render(Component.java:2303) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.Page.renderPage(Page.java:1018) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:195) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:865) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) [wicket-request-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284) [wicket-core-7.0.0-M6.jar:7.0.0-M6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.68.jar:7.0.68]
        at etm.contrib.integration.web.HttpRequestPerformanceFilter.doFilter(HttpRequestPerformanceFilter.java:74) [jetm-optional-1.2.3.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) [spring-security-web-4.0.0.RELEASE.jar:na]
```

**Comment by ojacques** [comment]
@chavezom this looks to happen because of this line: https://github.com/devops-dojo/the-app/blob/master/monolithic/ui/src/main/java/io/github/zutherb/appstash/shop/ui/tracking/mixpanel/TrackingServiceImpl.java#L104

**Comment by chavezom** [comment]
Added code to enable/disable this feature. With this service disabled the logs are clean. If this is enabled the Java proxy needs to be setup because it sends the tracking data to api.mixpanel.com. 

See https://mixpanel.com
